# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hyperverses"
license = "MIT"
licenselink = "https://github.com/pfhawkins/hugo-hyperverses-theme/blob/master/LICENSE.md"
description = "A hugo theme for hypertext exploration."
homepage = "http://github.com/pfhawkins/hugo-hyperverses-theme"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "P.F. Hawkins"
  homepage = "hypervers.es"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
